# -*- coding: utf-8 -*-
"""Digit Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UekblZa-0yvDJtyA8X_M-ZHCGnOLlavg

<a href="https://colab.research.google.com/github/Meena-017/hand-digit/blob/main/IAD_HONORS_L_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the TensorFlow library and loads the MNIST dataset, which consists of 70,000 grayscale images of handwritten digits (0–9), each sized 28x28 pixels. The dataset is automatically split into a training set and a test set, where `x_train` and `y_train` contain the images and labels for training (60,000 samples), and `x_test` and `y_test` contain the images and labels for testing (10,000 samples). The printed shapes of these arrays help verify that the data has been loaded correctly and show the structure of the input and output data. This dataset is commonly used for training and evaluating models in image classification tasks, especially for beginners in deep learning.
"""

import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)
print("x_test shape:", x_test.shape)
print("y_test shape:", y_test.shape)

"""This code installs the required libraries (scikit-image, OpenCV, and TensorFlow) and then extracts meaningful features from the MNIST dataset using various image processing techniques. It uses the Histogram of Oriented Gradients (HOG) feature descriptor to capture edge and texture information from the images. Additionally, it computes image characteristics such as the mean and variance of pixel values, histogram equalization for contrast enhancement, and edge detection using the Canny algorithm. These features are then compiled into feature vectors for each image in both the training and test sets. The resulting features are saved into CSV files (`mnist_train_features.csv` and `mnist_test_features.csv`), which can be used for further analysis or machine learning model training."""

!pip install scikit-image opencv-python tensorflow
import tensorflow as tf
import numpy as np
import pandas as pd
from skimage.feature import hog
from skimage import exposure
import cv2
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
def extract_features(images):
    all_features = []
    for img in images:
        image_features = []
        fd, hog_image = hog(img, orientations=9, pixels_per_cell=(8, 8),
                            cells_per_block=(2, 2), visualize=True, channel_axis=None)
        image_features.extend(fd)

        equ = exposure.equalize_hist(img)
        image_features.append(np.mean(equ))

        edges = cv2.Canny(img, 100, 200)
        image_features.append(np.sum(edges))

        image_features.append(np.mean(img))

        image_features.append(np.var(img))

        all_features.append(image_features)

    return np.array(all_features)


train_features = extract_features(x_train)

test_features = extract_features(x_test)


train_df = pd.DataFrame(train_features)
train_df['label'] = y_train

test_df = pd.DataFrame(test_features)
test_df['label'] = y_test

train_df.to_csv('mnist_train_features.csv', index=False)
test_df.to_csv('mnist_test_features.csv', index=False)

print("Feature extraction and CSV creation complete.")

"""This code attempts to load the previously saved CSV files containing the MNIST dataset features using the `pandas` library. It first tries to read the `mnist_train_features.csv` and `mnist_test_features.csv` files. If successful, it prints the first few rows of each dataset to display a snapshot of the training and testing data. The code also includes error handling to catch various issues: if the files are not found, it will display a `FileNotFoundError` message; if the files are empty, it will display an `EmptyDataError` message; and if there's a problem with parsing the files, it will raise a `ParserError`. Any other unexpected errors are captured by a general exception handler, ensuring that the program doesn't crash unexpectedly."""

import pandas as pd

try:
    train_df = pd.read_csv('mnist_train_features.csv')
    test_df = pd.read_csv('mnist_test_features.csv')

    print("Training Data:")
    print(train_df.head())

    print("\nTesting Data:")
    print(test_df.head())

except FileNotFoundError:
    print("Error: One or both CSV files not found. Please make sure 'mnist_train_features.csv' and 'mnist_test_features.csv' exist in the current directory.")
except pd.errors.EmptyDataError:
    print("Error: One or both CSV files are empty.")
except pd.errors.ParserError:
    print("Error: Could not parse the CSV file(s). Check the file format.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""This code performs model training and evaluation using various machine learning algorithms on the MNIST dataset features stored in CSV files. After loading the training and testing data, it separates the features (`X_train` and `X_test`) from the labels (`y_train` and `y_test`). The script then defines a set of machine learning models, including K-Nearest Neighbors (KNN), Random Forest, Support Vector Machine (SVM), Decision Tree, and Logistic Regression. Each model is trained on the training data, and its performance is evaluated on the test data using multiple metrics: accuracy, precision, and F1 score. The code also prints a detailed classification report for each model, which includes precision, recall, and F1 score per class. Finally, it prints a summary comparison of the models' performance. Error handling is implemented to catch issues such as missing files or other unexpected errors."""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, f1_score, classification_report

try:
    train_df = pd.read_csv('mnist_train_features.csv')
    test_df = pd.read_csv('mnist_test_features.csv')

    X_train = train_df.drop('label', axis=1)
    y_train = train_df['label']
    X_test = test_df.drop('label', axis=1)
    y_test = test_df['label']

    models = {
        "KNN": KNeighborsClassifier(),
        "Random Forest": RandomForestClassifier(),
        "SVM": SVC(),
        "Decision Tree": DecisionTreeClassifier(),
        "Logistic Regression": LogisticRegression(max_iter=1000)
    }

    results = {}
    for name, model in models.items():
        print(f"Training {name}...")
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        results[name] = {
            "Accuracy": accuracy_score(y_test, y_pred),
            "Precision": precision_score(y_test, y_pred, average='weighted'),
            "F1 Score": f1_score(y_test, y_pred, average='weighted')
        }
        print(classification_report(y_test,y_pred))

    print("\nComparison of Model Performance:")
    for name, metrics in results.items():
        print(f"{name}:")
        for metric, value in metrics.items():
            print(f"  {metric}: {value:.4f}")
except FileNotFoundError:
    print("Error: One or both CSV files not found.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""Installing Gradio to deploy"""

!pip install gradio

"""This code creates a Gradio interface for a handwritten digit recognition system. It allows users to upload an image of a handwritten digit, select a machine learning model, and receive a prediction of the digit. The `predict_image` function first processes the uploaded image: it resizes the image to 28x28 pixels, converts it to grayscale, and extracts relevant features using the `extract_features` function. Depending on the model selected by the user (SVM, KNN, Random Forest, Decision Tree, or Logistic Regression), it uses the corresponding trained model to predict the digit and returns the result as a string. If there’s an error during prediction, it provides an error message. The Gradio interface is set up with an image input, a radio button for model selection, and a text output to display the prediction. The app is launched with debugging enabled to aid troubleshooting."""

import gradio as gr

def predict_image(image, model_choice):
    try:
        image = cv2.resize(image, (28, 28))
        image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        image_features = extract_features(np.array([image]))

        if model_choice == "SVM":
            prediction = svm_model.predict(image_features)[0]
        elif model_choice == "KNN":
            prediction = models["KNN"].predict(image_features)[0]
        elif model_choice == "Random Forest":
            prediction = models["Random Forest"].predict(image_features)[0]
        elif model_choice == "Decision Tree":
            prediction = models["Decision Tree"].predict(image_features)[0]
        elif model_choice == "Logistic Regression":
            prediction = models["Logistic Regression"].predict(image_features)[0]
        else:
            prediction = "Invalid model selected"

        return str(prediction)
    except Exception as e:
        return f"Error during prediction: {e}"

iface = gr.Interface(
    fn=predict_image,
    inputs=[
        gr.Image(type="numpy"),
        gr.Radio(["SVM", "KNN", "Random Forest", "Decision Tree", "Logistic Regression"], label="Choose a model")
    ],
    outputs="text",
    title="Handwritten Digit Recognition",
    description="Upload an image of a handwritten digit (0-9) and select a model to predict the digit."
)

iface.launch(debug=True)



!pip install -U gradio

share=True

!pip install opencv-python

import cv2
import numpy as np
import gradio as gr

def predict_image(image, model_choice):
    try:
        # Resize and convert image
        image = cv2.resize(image, (28, 28))
        image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        image_features = extract_features(np.array([image]))

        if model_choice == "SVM":
            prediction = svm_model.predict(image_features)[0]
        elif model_choice == "KNN":
            prediction = models["KNN"].predict(image_features)[0]
        elif model_choice == "Random Forest":
            prediction = models["Random Forest"].predict(image_features)[0]
        elif model_choice == "Decision Tree":
            prediction = models["Decision Tree"].predict(image_features)[0]
        elif model_choice == "Logistic Regression":
            prediction = models["Logistic Regression"].predict(image_features)[0]
        else:
            prediction = "Invalid model selected"

        return str(prediction)
    except Exception as e:
        return f"Error during prediction: {e}"

iface = gr.Interface(
    fn=predict_image,
    inputs=[
        gr.Image(type="numpy"),
        gr.Radio(["SVM", "KNN", "Random Forest", "Decision Tree", "Logistic Regression"], label="Choose a model")
    ],
    outputs="text",
    title="Handwritten Digit Recognition",
    description="Upload an image of a handwritten digit (0-9) and select a model to predict the digit."
)

iface.launch(share=True, debug=True)

!pip install opencv-python

import cv2
import numpy as np
import gradio as gr

def predict_image(image, model_choice):
    try:
        # Resize and convert image
        image = cv2.resize(image, (28, 28))
        image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

        # Flatten and normalize the image like typical MNIST input
        image_features = image.reshape(1, -1) / 255.0

        if model_choice == "SVM":
            prediction = svm_model.predict(image_features)[0]
        elif model_choice == "KNN":
            prediction = models["KNN"].predict(image_features)[0]
        elif model_choice == "Random Forest":
            prediction = models["Random Forest"].predict(image_features)[0]
        elif model_choice == "Decision Tree":
            prediction = models["Decision Tree"].predict(image_features)[0]
        elif model_choice == "Logistic Regression":
            prediction = models["Logistic Regression"].predict(image_features)[0]
        else:
            prediction = "Invalid model selected"

        return str(prediction)
    except Exception as e:
        return f"Error during prediction: {e}"

iface = gr.Interface(
    fn=predict_image,
    inputs=[
        gr.Image(type="numpy"),
        gr.Radio(["SVM", "KNN", "Random Forest", "Decision Tree", "Logistic Regression"], label="Choose a model")
    ],
    outputs="text",
    title="Handwritten Digit Recognition",
    description="Upload an image of a handwritten digit (0-9) and select a model to predict the digit."
)

iface.launch(share=True, debug=True)



!pip install opencv-python

import cv2
import numpy as np
import gradio as gr

def predict_image(image, model_choice):
    try:
        # Resize and convert image
        image = cv2.resize(image, (28, 28))
        image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
        image_features = extract_features(np.array([image]))

        if model_choice == "SVM":
            prediction = svm_model.predict(image_features)[0]
        elif model_choice == "KNN":
            prediction = models["KNN"].predict(image_features)[0]
        elif model_choice == "Random Forest":
            prediction = models["Random Forest"].predict(image_features)[0]
        elif model_choice == "Decision Tree":
            prediction = models["Decision Tree"].predict(image_features)[0]
        elif model_choice == "Logistic Regression":
            prediction = models["Logistic Regression"].predict(image_features)[0]
        else:
            prediction = "Invalid model selected"

        return str(prediction)
    except Exception as e:
        return f"Error during prediction: {e}"

iface = gr.Interface(
    fn=predict_image,
    inputs=[
        gr.Image(type="numpy"),
        gr.Radio(["SVM", "KNN", "Random Forest", "Decision Tree", "Logistic Regression"], label="Choose a model")
    ],
    outputs="text",
    title="Handwritten Digit Recognition",
    description="Upload an image of a handwritten digit (0-9) and select a model to predict the digit."
)

iface.launch(share=True, debug=True)

!pip install opencv-python

import cv2
import numpy as np
import gradio as gr

def predict_image(image, model_choice):
    try:
        # Resize and convert image
        image = cv2.resize(image, (28, 28))
        image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)

        # Flatten and normalize the image like typical MNIST input
        image_features = image.reshape(1, -1) / 255.0

        if model_choice == "SVM":
            prediction = svm_model.predict(image_features)[0]
        elif model_choice == "KNN":
            prediction = models["KNN"].predict(image_features)[0]
        elif model_choice == "Random Forest":
            prediction = models["Random Forest"].predict(image_features)[0]
        elif model_choice == "Decision Tree":
            prediction = models["Decision Tree"].predict(image_features)[0]
        elif model_choice == "Logistic Regression":
            prediction = models["Logistic Regression"].predict(image_features)[0]
        else:
            prediction = "Invalid model selected"

        return str(prediction)
    except Exception as e:
        return f"Error during prediction: {e}"

iface = gr.Interface(
    fn=predict_image,
    inputs=[
        gr.Image(type="numpy"),
        gr.Radio(["SVM", "KNN", "Random Forest", "Decision Tree", "Logistic Regression"], label="Choose a model")
    ],
    outputs="text",
    title="Handwritten Digit Recognition",
    description="Upload an image of a handwritten digit (0-9) and select a model to predict the digit."
)

iface.launch(share=True, debug=True)